tasks:
  - init: git remote set-url origin git@github.com:pavithra-nagarajan/pavithra-nagarajan-repo-folder-check.git && sed "s/\r$//" commit-command.sh | bash
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - revaturePro.revature-labs